meme_subreddits=[
'aww', 
'bigbangedmemes', 
'bonehurtingjuice', 
'deepfriedmemes', 
'facepalm', 
'meme', 
'MemeEconomy',
'dankmemes', 
'memes', 
'nukedmemes', 
'okbuddyretard', 
'PerfectTiming', 
'surrealmemes', 
'wackytictacs', 
'wholesomememes']
nsfw_subreddits=[
'enter',
'nsfw',
'subreddits']